### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by badcat** [virejdasani/CodeBox#2]
this looks interesting but the logo.. I can't. ;)

Here - this is for you. I hope you consider it.

<img width="402" alt="codepbox" src="https://user-images.githubusercontent.com/26096/141343315-09e22441-d359-4b59-bac4-13c8d7238447.png">
.

**Comment by virejdasani** [comment]
@badcat thanks a lot for making a new logo! I'll let Reddit decide:
https://www.reddit.com/r/makemychoice/comments/qs2i22/which_logo_looks_better/

**Comment by badcat** [comment]
Altered the typography. Quick anim. LMK if you want the SVG source. 
![codebox-anim-v02](https://user-images.githubusercontent.com/26096/142516085-fe59b13e-ba10-4173-a7a5-72d3a40591cd.gif)

**Comment by virejdasani** [comment]
@badcat this looks awesome, can you make a PR by replacing the older icons? In the assets folder, can you add the logo and this animation?
I'll merge it and use this logo in the next Code Box update!

**Comment by badcat** [comment]
@virejdasani Sure - (forgot to reply to this before I made the PR 🤦‍♂️) these should now be complete.

**Comment by badcat** [comment]
All looks good here. Just need to replace those videos 📹
