### ISSUE TITLE
AUto complete

### ISSUE THREAD

**Issue by firelotuz1** [virejdasani/CodeBox#4]
How do you enable auto-complete?

**Comment by virejdasani** [comment]
It is enabled by default. You just start typing and the editor should give you suggestions!
However, you do need to be connected to the internet for this to work

**Comment by firelotuz1** [comment]
Of course i have internet? Weird,minds doesn't, i can share video snippet shortly

**Comment by virejdasani** [comment]
@firelotuz1 please do, I'll look into it

**Comment by virejdasani** [comment]
@firelotuz1 any updates?
